"""Squadron Campaign Engine (SQE): abstracted war + one fully generated DCS package per sortie."""
APP_NAME = "Squadron Campaign Engine"
SHORT = "SQE"
__version__ = "0.8.7"
CAMPAIGN_EXT = ".sqe"
FORMAT_VERSION = 4
AUTHOR = ""        # put your name and contact (GitHub profile or email) here before you publish: DCS's EULA (4.1) wants the creator named on the missions
EULA_LINE = "THIS MATERIAL IS NOT MADE OR SUPPORTED BY EAGLE DYNAMICS SA."


def credit_line() -> str:
    by = f" Created by {AUTHOR}." if AUTHOR else ""
    return f"Generated by {APP_NAME} (SQE) v{__version__}.{by} {EULA_LINE}"
